spring:
  application:
    name: scaleVision


app:
  storage:
    # Ruta física para guardar el archivo
    path: ${DB_STORAGE_VIDEO}
    # URL para que el frontend consuma el archivo
    url: ${STORAGE_NGIX}



  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB

  mvc:
    async:
      request-timeout: 60000

