spring:
  application:
    name: scaleVision

  data:
    web:
      pageable:
        serialization-mode: via-dto

  # --- SECCIÓN DE BASE DE DATOS ACTUALIZADA ---
  datasource:
    # Usamos tus variables de entorno exactas
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Dialecto para que Hibernate hable MySQL correctamente
        dialect: org.hibernate.dialect.MySQLDialect
  # --------------------------------------------

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB

  mvc:
    async:
      request-timeout: 60000

app:
  storage:
    path: ${DB_STORAGE_VIDEO}
    url: ${STORAGE_NGIX}
  slicer:
    url: ${SLICER_API_URL}

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always